Give X perms to newly build executable

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -61,7 +61,12 @@ jobs:
           if [[ ! -d ${{ github.workspace }}/starknet-devnet-rs/target/release ]]; then
             curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
             pushd ${{ github.workspace }}/starknet-devnet-rs
-            cargo build --release 
+            cargo build --release
+            chmod +x ${{ github.workspace }}/starknet-devnet-rs/target/release/starknet-devnet
+            if ! -d [ ! -d ${{ github.workspace }}/starknet-devnet-rs/target/release ]]; then
+              echo "Failed to build starknet-devnet-rs"
+              exit 1
+            fi
             popd
           else
             echo "Found existing starknet-devnet-rs build, skipping compilation."
